HUC.Web/Controllers/ContactController.cs
using System.Web.Mvc;
using BotDetect.Web.UI.Mvc;
using HUC.Web.App.PageModels.Forms;

namespace HUC.Web.Controllers
{
    public class ContactController : BaseController
    {
        //
        // GET: /Site/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [CaptchaValidation("CaptchaCode", "SampleCaptcha", "Incorrect CAPTCHA code!")]
        public ActionResult Index(ContactFormModel model)
        {

            if (ModelState.IsValid)
            {
                new MailController().ContactForm(model).Deliver();

                AddSuccess("Your message has been sent.");
                return RedirectToAction("Index");
            }

            AddErrorModel();
            return View(model);
        }
    }
}

HUC.Web/Controllers/RequestController.cs
using System.Web.Mvc;
using HUC.Web.App.PageModels.Forms;

namespace HUC.Web.Controllers
{
    public class RequestController : BaseController
    {
        //
        // GET: /Site/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(DemoFormModel model)
        {

            if (ModelState.IsValid)
            {
                new MailController().DemoForm(model).Deliver();

                AddSuccess("Your request for a demo has been sent.");
                return RedirectToAction("Index");
            }

            AddErrorModel();
            return View(model);
        }

        public ActionResult DemoHome()
        {
            return PartialView();
        }

        public ActionResult DemoPod()
        {
            return PartialView();
        }
    }
}

HUC.Web/Controllers/SiteController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using HUC.Web.App.Testimonials;

namespace HUC.Web.Controllers
{
    public class SiteController : BaseController
    {
        //
        // GET: /Site/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Footer()
        {
            return PartialView();
        }

        public ActionResult IndexTestimonial()
        {
            var model = Database.GetAll<TestimonialModel>("WHERE IsDeleted = 0 AND IsShowOnHomepage = 1").OrderBy(x => Guid.NewGuid()).FirstOrDefault();

            return PartialView(model);
        }
    }
}

HUC.Web/Views/Site/Footer.cshtml
@model HUC.Web.App.PageModels.Forms.ContactFormModel

<div id="footer">
    <div class="container">
        <div class="content">
            <div class="width-50">
                <ul>
                    <li>
                        <h3>
                            Sitemap
                        </h3>
                    </li>
                    <li>
                        <a href="/">
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="/Course">
                            Our courses
                        </a>
                    </li>
                    <li>
                        <a href="/About/WhyUs">
                            Why us
                        </a>
                    </li>
                    <li>
                        <a href="/Request">
                            Request demo
                        </a>
                    </li>
                    @*<li>
                        <a href="/Funding">
                            Funding support
                        </a>
                    </li>*@
                    <li>
                        <a href="/Aimed">
                            Who is it aimed at?
                        </a>
                    </li>
                </ul>

                <ul>
                    <li>
                        <h3>
                            Company
                        </h3>
                    </li>
                    <li>
                        <a href="/About">
                            Who we are
                        </a>
                    </li>
                    <li>
                        <a href="/Contact">
                            Contact
                        </a>
                    </li>
                    <li>
                        <a href="/Privacy">
                            Privacy policy
                        </a>
                    </li>
                    <li>
                        <a href="/Conditions">
                            Conditions of usage
                        </a>
                    </li>
                </ul>               
            </div>

            <div class="width-50 contact">
                @using (Html.BeginForm("Index", "Contact", FormMethod.Post))
                {
                    <h3>
                        Contact us
                    </h3>

                    <div class="main-inputs">
                        @Html.TextBoxFor(x => x.Name, new { placeholder = "Your name" })
                        @Html.TextBoxFor(x => x.Email, new { placeholder = "Email address" })
                    </div>

                    <div class="message-area">
                        @Html.TextAreaFor(x => x.Message, new { placeholder = "Your message..." })
                    </div>

                    <input class="large-button orange" type="submit" value="Send" />
                }
            </div>
            <div class="copyright-social">
                <p class="copyright">
                    &copy; 2020 Ghost Digital &amp; Data. All rights reserved.
                </p>
                <ul class="social-buttons">
                    <li>
                        <a class="linkin" href="http://uk.linkedin.com/pub/julian-rose/21/753/704" target="_blank"></a>
                    </li>
                    <li>
                        <a class="twitter" href="https://twitter.com/heads_up_comp" target="_blank"></a>
                    </li>
                </ul>
            </div>
           
        </div>
        <div class="clear"></div>
    </div>
</div>

HUC.Web/Views/Site/Index.cshtml
@using HUC.Web.Models
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewBag.PageData = new PageDataModel
    {
        Title = "Home",
        ActivePage = "home"
    };
}

<div class="home-slider">
    <div class="container">
        <div class="content">
            <div class="slide">
                <div class="text-box">
                    <p>
                        Online, easy to use <strong>Legal Compliance Training</strong>
                    </p>
                    <a class="large-button orange" href="/Request">
                        Request a demo
                    </a>
                </div>
                <div class="image">
                    <img alt="Online, easy to use Legal Compliance Training" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/banner-image.png" />
                </div>
            </div>
        </div>
    </div>
</div>

<div class="dark-teal-bg home-links">
    <div class="container">
        <div class="content">
            <img class="prev servicebanner-prev" alt="Previous" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/large-white-arrow-prev.png" />
            <ul class="servicebanner">
                <li class="open" style="border-right: none;">
                    <a href="/Course">
                        <img class="icon" alt="OUR COURSES" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/home-courses.png" />
                        <span>
                            <label>
                                OUR COURSES
                            </label>
                        </span>
                    </a>
                </li>
                @*<li>
                    <a href="/Funding">
                        <img class="icon" alt="" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/home-funding.png" />
                        <span>
                            <label>
                                FUNDING SUPPORT
                            </label>
                        </span>
                    </a>
                </li>
                <li class="last">
                    <a href="Consultancy">
                        <img class="icon" alt="" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/home-consultancy.png" />
                        <span>
                            <label>
                                CONSULTANCY SERVICES
                            </label>
                        </span>
                    </a>
                </li>*@
            </ul>
            <img class="next servicebanner-next" alt="Next" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/large-white-arrow-next.png" />
        </div>
        <div class="clear"></div>
    </div>
</div>

@Html.Action("DemoHome", "Request")

<div class="standard-bg">
    <div class="container">
        <div class="content">
            <div class="home-info">
                <ul>
                    <li>
                        <img class="pic" alt="Who is it aimed at" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/home-col1-image.png" />
                        <h4>
                            Who is it aimed at
                        </h4>
                        <p>
                            Training Courses was initially set up to assist Legal firms to be compliant with the ...
                            <a href="/Aimed">
                                Read more >
                            </a>
                        </p>
                    </li>
                    @*<li>
                        <img class="pic" alt="" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/home-col2-image.png" />
                        <h4>
                            Funding support available
                        </h4>
                        <p>
                            Training Courses are dedicated to helping Law firms address the latest ...
                            <a href="/Funding">
                                Read more >
                            </a>
                        </p>
                    </li>*@
                </ul>
                
                @Html.Action("IndexTestimonial")
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {

        $(".home-slider .container .content").AnySlider({
            interval: 5000
        });

    });
</script>

HUC.Web/Views/Site/IndexTestimonial.cshtml
@model HUC.Web.App.Testimonials.TestimonialModel

@if (Model != null)
{
    <div class="testimonial-box">
        <p>
            <img class="open-quote" alt="open quote" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/testimonial-open-quote.png" />

            @Model.BodyCopy

            <img class="close-quote" alt="close quote" src="@(HttpContext.Current.Request.ApplicationPath.Length > 1 ? HttpContext.Current.Request.ApplicationPath : string.Empty)/_Content/images/testimonial-close-quote.png" />
        </p>
        <label>
            @Model.FullName
            
            @if (!String.IsNullOrWhiteSpace(Model.CompanyName))
            {
                <br />
                @:@Model.CompanyName
            }
        </label>
    </div>
}